name: Github Actions/Cypress Demo
on: [push]
jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Fetch code
      - run: ls -a /bin
      - run: yarn
