name: Github Actions/Cypress Demo
on: [push]
jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Fetch code
      - run: yarn install --frozen-lockfile --quiet
      - run: yarn e2e:ci 
