name: Github Actions/Cypress Demo
on: [push]
jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Fetch code
      - uses: c-hive/gha-yarn-cache@v2

      - name: Install JS dependencies
        run: yarn install

      - name: Unit Test
        run: yarn test

      # - name: E2E Testing
      #   run: |
      #     yarn e2e:ci

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: artifacts
      #     path: ./artifacts
