name: Github Actions/Cypress Docker Compose
on: workflow_dispatch
jobs:
  cypress-e2e-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Fetch code

      - run: docker-compose up --abort-on-container-exit --exit-code-from e2e
        name: E2E Tests on Docker Compose

      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ./artifacts
