name: Github Actions/Cypress Demo
on: [push]
jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Fetch code


      - name: Cache node modules
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
            **/.eslintcache
            ${{ steps.yarn-cache-dir-path.outputs.dir }}

          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Packages
        run: yarn install --frozen-lockfile --quiet

      - name: E2E Testing
        run: |
          yarn e2e:ci

      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ./artifacts
