name: Github Actions/Cypress Demo
on: [push]
jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Fetch code

      - uses: c-hive/gha-yarn-cache@v2
        name: Handles caching node_modules

      - name: Install JS dependencies
        run: yarn install --froze-lockfile --quiet

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start

      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ./artifacts
